### ISSUE TITLE
where is the ppmn_narr_list.json file in the sam_refine_png.py?

### ISSUE THREAD

**Issue by LaibinChang** [nini0919/DiffPNG#1]
png_data = json.load(open('/media/disk2/ydn/prompt-to-prompt/ppmn_narr_list.json'))

**Comment by nini0919** [comment]
You can try this command: CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --master_port 14321 --nproc_per_node 4 --nnodes 1 segment-anything-third-party/sam-png/segment_anything_mode.py. The file ppmn_narr_list is uploaded at the root of this project.
